### ISSUE TITLE
readme suggestion: unary function

### ISSUE THREAD

**Issue by dizzyone** [JorgeBucaran/classcat#11]
Perhaps you could mention that cc is a unary function (arity of 1, accepts 1 argument) and not variadic (indefinite arity).

“variable arguments” confused me a little at first, I think using the mathematical terms is more concise, easier to google as well than linking to mdn’s argument page.

**Comment by JorgeBucaran** [comment]
@dizzyone Sounds good. How and specifically where do you think we could write that? 🤔

**Comment by dizzyone** [comment]
Maybe you could start the usage section with > “Classcat is a unary function (accepts a single argument) expecting an array of elements or an object of keys...”

Under the credits section you could replace the part about variable arguments (variable number of arguments):
> “the difference between cc and classnames is that classnames is a variadic function that accepts an indefinite/variable number of arguments, where as cc only accepts a single argument.”

Writing this from my phone so cant make a PR, but I think that would make it much more clear.

**Comment by JorgeBucaran** [comment]
Done! 🎉 
> b76ab52d2063a423b2977e5c2f2005101eed0785 Improve documentation and type info. Close #11. Thanks @dizzyone.
