### ISSUE TITLE
Fix CodePen Example

### ISSUE THREAD

**Issue by colshacol** [JorgeBucaran/classcat#12]
https://codepen.io/colshacol/pen/MOzMOQ?editors=0010

I went to check out the [CodePen example](https://codepen.io/JorgeBucaran/pen/GMRjRB) and found that it did not work.

<img width="789" alt="screenshot 2017-11-30 09 55 38" src="https://user-images.githubusercontent.com/19484365/33440086-abfb5ad0-d5b4-11e7-9180-f42e53c2809e.png">

I referred to the [hyperapp docs](https://github.com/hyperapp/hyperapp) and found that `app.view` needed to be composed of two functions rather than one function that takes two arguments.

Then I got a similar error with `actions.toggle` and found in the docs that actions should be structured the same way as the view.

[I made these changes on a "fork"](https://codepen.io/colshacol/pen/MOzMOQ) for you to review and update your existing CodePen example.

---

_... And, for compliance and to make myself feel like a real contributor..._

## Expected:
When going to check out the CodePen example, the example works.

## Actual:
When going to check out the CodePen example, the example not works.

## Steps to Reproduce:
Go checkout the CodePen example.

**Comment by JorgeBucaran** [comment]
Fixed! Thanks 🙏
