### ISSUE TITLE
When all child elements are `false` the object key is still included

### ISSUE THREAD

**Issue by developerdizzle** [JorgeBucaran/classcat#13]
Eg: 
```js
classcat([
  "tab",
  {
    tab: {
      "--success": false,
    }
  }
]); // "tab tab"
```

https://codepen.io/dizzle/pen/baOjjj

I would expect it not to be included in the class list, but is this by design?

**Comment by JorgeBucaran** [comment]
@developerdizzle I think this should be considered a bug, and only one `tab` should be included.

**Comment by developerdizzle** [comment]
I added this to the codepen, but I found a workaround:
```js
classcat([
  {
    tab: {
      " ": true,
      "--success": false,
    }
  }
]);
```

Also noticed that[ `classNames` has a dedupe version ](https://github.com/jedwatson/classnames#alternate-dedupe-version)

**Comment by JorgeBucaran** [comment]
@developerdizzle You are right this is a case of duplication, but perhaps simple one we should be able to take care **without** having to dedupe the entire result.

**Comment by developerdizzle** [comment]
Agreed; I think a full dedupe is overkill.  I'll see if I can spend some time on it tomorrow and hopefully find a concise solution.

**Comment by developerdizzle** [comment]
@JorgeBucaran I think I'm close, but this test is failing https://github.com/JorgeBucaran/classcat/blob/master/tests/index.test.js#L37-L49

Is this a legit use-case?  I don't see it in the documentation and it seems to go against being a unary function.

**Comment by JorgeBucaran** [comment]
Hmm, it looks like a perfectly valid used case. 🤔

**Comment by developerdizzle** [comment]
Is it supposed to be documented somewhere?

**Comment by JorgeBucaran** [comment]
It's definitely not well documented.

**Comment by developerdizzle** [comment]
@JorgeBucaran https://github.com/JorgeBucaran/classcat/pull/14 simplifies some things, and fixes this bug, but it does break that case.  Curious to hear what you think.

**Comment by developerdizzle** [comment]
I think part of the complication is that `prefix` is used for both the separator between class names, and the prefix for child elements of an object.

**Comment by JorgeBucaran** [comment]
Are you using this feature? I have to admit I wish I hadn't added it. 😅

**Comment by developerdizzle** [comment]
The "prefix" feature whose test results in "foo-bar-baz" ?  I am not!  And honestly, if I was, I'd expect it to be a true prefix for each class (not a separator), eg: "-foo -bar -baz"

**Comment by developerdizzle** [comment]
I'm not sure how many implementations it would break by removing it, though... 😟

**Comment by JorgeBucaran** [comment]
Exactly, people seem to have different expectations for what this should or shouldn't do. It was "natural" to support when I made this, but I should have let it for later when there was a real need. 

Well, there's always 2.0.

**Comment by developerdizzle** [comment]
I'll leave this and the PR open, but feel free to request changes or reject it as a whole.
