### ISSUE TITLE
Classes order causing issue

### ISSUE THREAD

**Issue by pedroborges** [JorgeBucaran/classcat#19]
I'm using a utility framework with Classcat and it wasn't rendering the classes for one of the checks even thought it was evaluating to `true`. Switching the order of the classes, or renaming the first class made it work.

```diff
cc([
    'mr-auto px-1 py-0.5 font-bold tracking-lg rounded',
    {
        'text-black bg-white': isNew(order),
-       'text-white bg-grey': isPending(order), // don't work
+       'bg-grey text-white': isPending(order), // works
// or
+       'text-green bg-grey': isPending(order), // works
        'text-white bg-grey': isAccepted(order),
        'text-red bg-white': isExpired(order),
    }
])
```

I'm reporting because it looks like a bug.

**Comment by JorgeBucaran** [comment]
@pedroborges Thanks. What classcat version were you using and can you post the original code you used? I don't understand what the <samp>diff</samp> is supposed to show.

I am trying to repro this issue [here](https://codepen.io/JorgeBucaran/pen/GMRjRB) to no avail. 🤔

**Comment by JorgeBucaran** [comment]
@pedroborges Could this be a bug with your CSS and not in classcat?

**Comment by pedroborges** [comment]
Thanks for the input guys! I have reverted the order of the classes for that particular item and it's working fine today. Yesterday I must have messed it somehow 😕
