### ISSUE TITLE
 imported could not be resolved

### ISSUE THREAD

**Issue by z543** [jorgebucaran/classcat#20]
```
// Install with npm
npm i classcat
```

```js
// foo.tsx
import classcat from 'classcat'
```

bundle with rollup(transpile with typescript)

show warning:  'classcat' is imported by src\js\foo.tsx, but could not be resolved – treating it as an external dependency

no problem with other import

**Comment by jorgebucaran** [comment]
@z543 I have no idea. This is probably an error in your rollup configuration. Do you have a sample project I can clone and check myself?

**Comment by z543** [comment]
it seems my mistake,
I change code to
```js
import classcat from 'classcat/src/index.js'
```
not warning

**Comment by jorgebucaran** [comment]
@z543 That sounds like an issue in how tsc is resolving the <samp>baseUrl</samp>. Can you show me your tsconfig.json?

**Comment by z543** [comment]
sorry, it still my fault.

according to [treating-module-as-external-dependency](https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency)

I add plugin 'rollup-plugin-node-resolve',
and there is no problem

**Comment by jorgebucaran** [comment]
@z543 So, is it solved?

**Comment by z543** [comment]
yes

**Comment by jorgebucaran** [comment]
🎉🎉
