### ISSUE TITLE
Don't publish the benchmark

### ISSUE THREAD

**Issue by userpixel** [jorgebucaran/classcat#21]
The `./bench` dir contains a benchmarking code that is not part of the module strictly speaking so it doesn't need to be published. On the same line of argument we can skip publishing the tests as well.

#### Suggested solution

Add an [`.npmignore` file](https://docs.npmjs.com/misc/developers) to the root with this content:

```
bench/
tests/
```

That's all! 👍

**Comment by jorgebucaran** [comment]
@userpixel Good call, let's fix that.

**Comment by jorgebucaran** [comment]
So, I guess this is not enough?

https://github.com/jorgebucaran/classcat/blob/67f66031e3beecb232c1955ce829b8b28029a1d3/package.json#L11-L15

**Comment by jorgebucaran** [comment]
<img width="663" alt="screen shot 2018-04-11 at 22 42 47" src="https://user-images.githubusercontent.com/56996/38620569-b4844e04-3dd9-11e8-80f1-5b5345cffc8d.png">

The benchmarks are not published to npm as I'm using the [`files`](https://docs.npmjs.com/files/package.json#files) field in package.json which works similarly to .npmignore.

Case solved.
