### ISSUE TITLE
Running benchmarks locally requires build

### ISSUE THREAD

**Issue by eps1lon** [jorgebucaran/classcat#22]
```bash
$ git clone https://github.com/jorgebucaran/classcat.git
$ cd classcat/bench
$ npm i
$ node .
[...]
Error: Cannot find module '../'
[...]
```
Only after running `npm run build` and applying to following patch to `bench/index.js` 
```git
-const cc = require("../")
+const cc = require("../dist/classcat")
```
was I able to run the benchmarks as described in `bench/README.md`

**Comment by jorgebucaran** [comment]
Thanks for finding out. I've added a new npm script `npm run bench` and simplified how running the benchmarks work.

Thanks! 🎉 

https://github.com/jorgebucaran/classcat/blob/0bfd90dfbd9b183f852d3b0070955bd7e1683e53/package.json#L29
