### ISSUE TITLE
Bundling error with 3.1.1

### ISSUE THREAD

**Issue by HugoGiraudel** [jorgebucaran/classcat#25]
Good morning! 👋

As per 3.1.1 (which changed bundling system to `iife`), Webpack bundling of `classcat` causes the following error:

```
TypeError: classcat__WEBPACK_IMPORTED_MODULE_1___default(...) is not a function
```

With all due respect, I suggest not changing what your library exports in a patch. 😄

You probably should roll back to 3.1.0 or publish 3.1.2 with `amd` bundling and offer `iife` in 4.0.0 or optionally in a minor along side with the existing export interface.

Hope it helps!

**Comment by jorgebucaran** [comment]
@HugoGiraudel I don't understand. Why doesn't webpack pick up the module field from pkg.json pointing to the ES6 source? 

https://github.com/jorgebucaran/classcat/blob/4ace17d95c5d37e5de90d81026add6dec52ae903/package.json#L6

In any rate, what should we export then?

> With all due respect, I suggest not changing what your library exports in a patch. 

Thanks, makes sense.

**Comment by jorgebucaran** [comment]
@HugoGiraudel Could you share the part of your webpack config where you specify the `target`? I suppose it is `node`?

**Comment by jorgebucaran** [comment]
Anyway, here is [3.1.2](https://unpkg.com/classcat@3.1.2/dist/classcat.js) unbreaking the issue. 

3.1.1 will be remembered as the rogue one.
