### ISSUE TITLE
React generates empty classnames in DOM if value is an empty string

### ISSUE THREAD

**Issue by vladshcherbin** [jorgebucaran/classcat#30]
Same as https://github.com/JedWatson/classnames/issues/182

In react, if the value passed to `className` is an empty string, the html output will be `<div class=""/>`. In order to have a clean `<div />`, `undefined` should be passed.

Any idea how this can be solved? There is a [PR](https://github.com/JedWatson/classnames/pull/183) in `classnames`, what do you think about this in `classcat`? :)

**Comment by jorgebucaran** [comment]
@vladshcherbin Can `<div class=""/>` break an app? Incidentally, Hyperapp's output is: `<div class />`.

**Comment by vladshcherbin** [comment]
@jorgebucaran I don't think it can break an app.

Returning `undefined` just gives a clean html output without empty classes.

**Comment by jorgebucaran** [comment]
@vladshcherbin Return `undefined` and you may also end up with `"undefined my-class"` if you're concatenating Classcat's output with a string as someone [already pointed out](https://github.com/JedWatson/classnames/pull/183#issuecomment-435227542) in the classNames PR. 

React, Hyperapp should solve this, not Classcat. I want a clean DOM too, but changing Classcat to monkey-patch a JavaScript framework is worse.

I'll fix this in Hyperapp in https://github.com/jorgebucaran/hyperapp/issues/754.

Thanks! 👋

**Comment by vladshcherbin** [comment]
@jorgebucaran sure, thanks :)

What do you think of a separate export that will return `undefined` for people, confident it won't break anything?
