### ISSUE TITLE
v5 not working with create-react-app

### ISSUE THREAD

**Issue by tu4mo** [jorgebucaran/classcat#38]
v5 breaks in a `create-react-app` project. Maybe related to `exports` in `package.json` and webpack 4?

https://codesandbox.io/s/hidden-rain-pldjt?file=/src/App.js

**Comment by jorgebucaran** [comment]
Classcat should work on Node 8, 10, 12, 14, and so on without any extra work on your side. Hopefully. 

Are we missing anything in `package.json` to make Webpack find the export? I'm not super familiar with Webpack.

**Comment by tu4mo** [comment]
Tried adding `"module": "index.js"` and it seemed to work. I'm not very familiar with the new `exports` field.

**Comment by jorgebucaran** [comment]
Okay, cool, let's add that for now. 👍
