### ISSUE TITLE
Add babel-plugin-optimize-clsx to Readme

### ISSUE THREAD

**Issue by minushabens** [jorgebucaran/classcat#39]
I think we should link in Readme this amazing project: https://github.com/merceyz/babel-plugin-optimize-clsx.

I [just asked](https://github.com/merceyz/babel-plugin-optimize-clsx/issues/19) to add this library as a default.

**Comment by minushabens** [comment]
This lib doesn't support variadic arguments so isn't compatible with the output of that plugin. Sorry.

**Comment by jorgebucaran** [comment]
Correct. And I don't intend to support variadic arguments either.
