### ISSUE TITLE
BUG: Incorrect typings due to missing supported types

### ISSUE THREAD

**Issue by motss** [jorgebucaran/classcat#40]
## Description

While the function already supports the following missing types, the typings does not and this renders TypeScript to not be able to run the type check without any errors.

## Proposals

1. Use safer `unknown` to accept any types
   ```
   export as namespace Classcat

   /**
    * @param names A string, array or object of CSS class names (as keys).
    * @returns The class attribute string.
    */
   export default function (names: unknown): string
   ```
1. Add missing `undefined` and `null`
   ```diff
   - export type Class = string | number | ClassObject | ClassArray
   + export type Class = string | number | undefined | null | ClassObject | ClassArray
   ...
   ```

**Comment by jorgebucaran** [comment]
I think I prefer option 2. Want to PR me that change? 👍

**Comment by motss** [comment]
@jorgebucaran Thanks for the preferred option. I have raised #41 to fix this issue.

**Comment by motss** [comment]
@jorgebucaran Thanks for merging the PR. What's the plan to release a new patch for the fix?

**Comment by jorgebucaran** [comment]
Hey @motss, sorry for the delay here. I just published a new patch with this. 🙌
